[tool.poetry]
name = "lookyloo-monitoring"
version = "0.1.0"
description = ""
authors = ["Raphaël Vinot <raphael@vinot.info>"]

[tool.poetry.dependencies]
python = "^3.8"
pylookyloo = "^1.10.0"
plotly = "^5.5.0"
jupyter-dash = "^0.4.0"
jupyterlab = "^3.2.8"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
run_captures = "bin.run_captures:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
