[tool.poetry]
name = "lookyloo-monitoring"
version = "0.1.0"
description = ""
authors = ["Raphaël Vinot <raphael@vinot.info>"]

[tool.poetry.dependencies]
python = "^3.10"
pylookyloo = "^1.16.0"
plotly = "^5.11.0"
jupyter-dash = "^0.4.2"
jupyterlab = "^3.5.1"
pandas = "^1.5.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
run_captures = "bin.run_captures:main"

[build-system]
requires = ["poetry-core>=1.1"]
build-backend = "poetry.core.masonry.api"
